capital = []
    capital.append('- - Seleccione un Municipio- -')
    capital.append("Libertador")

amazonas = []
    amazonas.append('- - Seleccione un Municipio- -')
    amazonas.append("Alto Orinoco")
    amazonas.append("Atabapo")
    amazonas.append("Atures")
    amazonas.append("Autana")
    amazonas.append("Manapiare")
    amazonas.append("Maroa")
    amazonas.append("Río Negro")


anzoategui = []
    anzoategui.append('- - Seleccione un Municipio- -')
    anzoategui.append("Anaco")
    anzoategui.append("aragua")
    anzoategui.append("Bolívar")
    anzoategui.append("Bruzual")
    anzoategui.append("Cajigal")
    anzoategui.append("Carvajal")
    anzoategui.append("Diego Bautista Urbaneja")
    anzoategui.append("Freites")
    anzoategui.append("Guanipa")
    anzoategui.append("Guanta")
    anzoategui.append("Independencia")
    anzoategui.append("Libertad")
    anzoategui.append("McGregor")
    anzoategui.append("miranda")
    anzoategui.append("Monagas")
    anzoategui.append("Peñalver")
    anzoategui.append("Píritu")
    anzoategui.append("San Juan de Capistrano")
    anzoategui.append("Santa Ana")
    anzoategui.append("Simén Rodriguez")
    anzoategui.append("Sotillo")


apure = []
    apure.append('- - Seleccione un Municipio- -')
    apure.append("Achaguas" )
    apure.append("Biruaca")
    apure.append("Muñoz")
    apure.append("Páez")
    apure.append("Pedro Camejo")
    apure.append("Rómulo Gallegos")
    apure.append("San Fernando")

aragua = []
    aragua.append('- - Seleccione un Municipio- -')
    aragua.append("Bolívar")
    aragua.append("Camatagua")
    aragua.append("Francisco Linares Alcántara")
    aragua.append("Girardot")
    aragua.append("José Angel Lamas")
    aragua.append("José Félix Ribas")
    aragua.append("José Rafael Revenga")
    aragua.append("Libertador")
    aragua.append("Mario Briceño Iragorry")
    aragua.append("San Casimiro")
    aragua.append("San Sebastián)")
    aragua.append("Santiago Mariño")
    aragua.append("Santos Michelena")
    aragua.append("Sucre")
    aragua.append("To")
    aragua.append("Urdaneta")
    aragua.append("Zamora")

barinas = []
    barinas.append('- - Seleccione un Municipio- -')
    barinas.append("Alberto Arvelo Torrealba")
    barinas.append("Andrés Eloy Blanco")
    barinas.append("Antonio José de Sucre")
    barinas.append("Arismendi")
    barinas.append("barinas")
    barinas.append("Bolé")
    barinas.append("Cruz Paredes")
    barinas.append("Ezequiel Zamora")
    barinas.append("Obispos")
    barinas.append("Pedraza")
    barinas.append("Rojas")
    barinas.append("Sosa")


bolivar = []
    bolivar.append('- - Seleccione un Municipio- -')
    bolivar.append("Caroní" )
    bolivar.append("Cedeño")
    bolivar.append("El Callao" )
    bolivar.append("Gran Sabana")
    bolivar.append("Heres)" )
    bolivar.append("Piar")
    bolivar.append("Raúl Leoni" )
    bolivar.append("Roscio")
    bolivar.append("Sifontes" )
    bolivar.append("Sucre")
    bolivar.append("Padre Pedro Chien" )

carabobo = []
    carabobo.append('- - Seleccione un Municipio- -')
    carabobo.append("Bejuma (Bejuma)")
    carabobo.append("Carlos Arvelo (G\u00FCig\u00FCe)")
    carabobo.append("Diego Ibarra (Mariara)")
    carabobo.append("Guacara (Guacara)")
    carabobo.append("Juan José Mora (Morón)")
    carabobo.append("Libertador (Tocuyito)")
    carabobo.append("Los Guayos (Los Guayos)")
    carabobo.append("miranda (miranda)")
    carabobo.append("Montalbán (Montalbán)")
    carabobo.append("Naguanagua (Naguanagua)")
    carabobo.append("Puerto Cabello (Puerto Cabello)")
    carabobo.append("San Diego")
    carabobo.append("San Joaquín (San Joaquín)")
    carabobo.append("Valencia (Valencia)")

cojedes = []
    cojedes.append('- - Seleccione un Municipio- -')
    cojedes.append("Anzoátegui (cojedes)")
    cojedes.append("Falcón (Tinaquillo)" )
    cojedes.append("Girardot (El Baúl)")
    cojedes.append("Lima Blanco (Macapo)")
    cojedes.append("Pao de San Juan Bautista (El Pao)")
    cojedes.append("Ricaurte (Libertad)")
    cojedes.append("Rómulo Gallegos (Las Vegas)")
    cojedes.append("San Carlos (San Carlos)")
    cojedes.append("Tinaco (Tinaco)")


delta = []
    delta.append('- - Seleccione un Municipio- -')
    delta.append("Antonio Díaz (Curiapo)" )
    delta.append("Casacoima (Sierra Imataca)")
    delta.append("Pedernales (Pedernales)")
    delta.append("Tucupita (Tucupita)")

falcon = []
    falcon.append('- - Seleccione un Municipio- -')
    falcon.append("Acosta (San Juan de los Cayos)")
    falcon.append("Bolívar (San Luis)")
    falcon.append("Buchivacoa (Capatárida)")
    falcon.append("Cacique Manaure (Yaracal)")
    falcon.append("Carirubana (Punto Fijo)")
    falcon.append("Colina (La Vela de Coro)")
    falcon.append("Dabajuro (Dabajuro)")
    falcon.append("Democracia (Pedregal)")
    falcon.append("Falcón (Pueblo Nuevo)")
    falcon.append("Federación (Churuguara)")
    falcon.append("Jacura (Jacura)")
    falcon.append("Los Taques (Santa Cruz de Los Taques)")
    falcon.append("Mauroa (Mene de Mauroa)")
    falcon.append("Miranda (Santa Ana de Coro)")
    falcon.append("Monseñor Iturriza (Chichiriviche)")
    falcon.append("Palmasola (Palmasola)")
    falcon.append("Petit (Cabure)")
    falcon.append("Píritu (Píritu)")
    falcon.append("San Francisco (Mirimire)")
    falcon.append("Silva (Tucacas)")
    falcon.append("Sucre (La Cruz de Taratara)")
    falcon.append("Tocópero (Tocópero)")
    falcon.append("Unión (Santa Cruz de Bucaral)")
    falcon.append("Urumaco (Urumaco)")
    falcon.append("Zamora (Puerto Cumarebo)")

guarico = []
    guarico.append('- - Seleccione un Municipio- -')
    guarico.append("Camaguán (Camaguán).")
    guarico.append("Chaguaramas (Chaguaramas)" )
    guarico.append("El Socorro (El Socorro)" )
    guarico.append("Sebastian Francisco de Miranda (Calabozo)" )
    guarico.append("José Félix Ribas (Tucupido)" )
    guarico.append("José Tadeo Monagas (Altagracia de Orituco)" )
    guarico.append("Juan Germán Roscio (San Juan de Los Morros)" )
    guarico.append("Julián Mellado (El Sombrero)" )
    guarico.append("Las Mercedes (Las Mercedes)" )
    guarico.append("Leonardo Infante (Valle de La Pascua)" )
    guarico.append("Pedro Zaraza (Zaraza)" )
    guarico.append("Ortiz (Ortiz)" )
    guarico.append("San Gerónimo de Guayabal (Guayabal)" )
    guarico.append("San José de Guaribe (San José de Guaribe)" )
    guarico.append("Santa Maru\00e1a de Ipire (Santa María de Ipire)" )

lara = []
    lara.append('- - Seleccione un Municipio- -')
    lara.append("Andrés Eloy Blanco (Sanare)" )
    lara.append("Crespo (Duaca)")
    lara.append("Iribarren (Barquisimeto)")
    lara.append("Jiménez (Quibor)")
    lara.append("Morán (El Tocuyo)")
    lara.append("Palavecino (Cabudare)")
    lara.append("Simón Planas (Sarare)")
    lara.append("Torres (Carora)")
    lara.append("Urdaneta (Siquisique)")

merida = []
    merida.append('- - Seleccione un Municipio- -')
    merida.append("Alberto Adriani (El Vigía)")
    merida.append("Andrés Bello (La Azulita)")
    merida.append("Antonio Pinto Salinas (Santa Cruz de Mora)")
    merida.append("Aricagua (Aricagua)")
    merida.append("Arzobispo Chacón (Canaguá)")
    merida.append("Campo Elías (Ejido)")
    merida.append("Caracciolo Parra Olmedo (Tucaní)")
    merida.append("Cardenal Quintero (Santo Domingo)")
    merida.append("Guaraque (Guaraque)")
    merida.append("Julio César Salas (Arapuey)")
    merida.append("Justo Briceño (Torondoy)")
    merida.append("Libertador (Mérida)")
    merida.append("Miranda (Timotes)")
    merida.append("Obispo Ramos de Lora (Santa Elena de Arenales)")
    merida.append("Padre Noguera (Santa María de Caparo)")
    merida.append("Pueblo Llano (Pueblo Llano)")
    merida.append("Rangel (Mucuchíes)")
    merida.append("Rivas Dávila (Bailadores)")
    merida.append("Santos Marquina (Tabay)")
    merida.append("Sucre (Lagunillas)")
    merida.append("To (To)")
    merida.append("Tulio Febres Cordero (Nueva bolivarvia)")
    merida.append("Zea (Zea)")

miranda = []
    miranda.append('- - Seleccione un Municipio- -')
    miranda.append("Acevedo (Caucagua)" )
    miranda.append("Andrés Bello (San José de Barlovento)")
    miranda.append("Baruta (Baruta)")
    miranda.append("Brión (Higuerote)")
    miranda.append("Buroz (Mamporal)")
    miranda.append("Carrizal (Carrizal)")
    miranda.append("Chacao (Chacao)")
    miranda.append("Cristóbal Rojas (Charallave)")
    miranda.append("El Hatillo (Santa Rosalía de Palermo)")
    miranda.append("Guaicaipuro (Los Teques)")
    miranda.append("Independencia (Santa Teresa del Tuy)")
    miranda.append("Lander (Ocumare del Tuy)")
    miranda.append("Los Salias (San Antonio de los Altos)a")
    miranda.append("Páez (Río Chico)")
    miranda.append("Páez Castillo (Santa Lucía)")
    miranda.append("Pedro Gual (Cúpira)")
    miranda.append("Plaza (Guarenas)")
    miranda.append("Simón Bolívar (San Francisco de Yare)")
    miranda.append("Sucre (Petare)")
    miranda.append("Urdaneta (Cúa)")
    miranda.append("Zamora (Guatire)")

monagas = []
    monagas.append('- - Seleccione un Municipio- -')
    monagas.append("Acosta (San Antonio de Capayacuar)" )
    monagas.append("Aguasay (Aguasay)")
    monagas.append("Bolívar (Caripito)")
    monagas.append("Caripe (Caripe)")
    monagas.append("Cedeño (Caicara)")
    monagas.append("Ezequiel Zamora (Punta de Mata)")
    monagas.append("Libertador (Temblador)")
    monagas.append("Maturín (Maturín)")
    monagas.append("Piar (aragua de Maturín)")
    monagas.append("Punceres (Quiriquire)")
    monagas.append("Santa Bárbara (Santa Bárbara)")
    monagas.append("Sotillo (Barrancas del Orinco)")
    monagas.append("Uracoa (Uracoa)")

nuevaEsparta = []
    nuevaEsparta.append('- - Seleccione un Municipio- -')
    nuevaEsparta.append("Antolín del Campo (La Plaza de Paraguachí)")
    nuevaEsparta.append("Arismendi (La Asunción)")
    nuevaEsparta.append("Díaz (San Juan Bautista)")
    nuevaEsparta.append("García (El Valle del Espíritu Santo)")
    nuevaEsparta.append("Gómez (Santa Ana)")
    nuevaEsparta.append("Maneiro (Pampatar)")
    nuevaEsparta.append("Marcano (Juan Griego)")
    nuevaEsparta.append("Mariño (Porlamar)")
    nuevaEsparta.append("Península de Macanao (Boca de Río)")
    nuevaEsparta.append("Tubores (Punta de Piedras)")
    nuevaEsparta.append("Villalba (San Pedro de Coche)")

portuguesa = []
    portuguesa.append('- - Seleccione un Municipio- -')
    portuguesa.append("Agua Blanca (Agua Blanca)" )
    portuguesa.append("Araure (Araure)")
    portuguesa.append("Esteller (Píritu)")
    portuguesa.append("Guanare (Guanare)")
    portuguesa.append("Guanarito (Guanarito)")
    portuguesa.append("Monseñor José Vicente de Unda (Chabasquén de Unda)")
    portuguesa.append("Ospino (Ospino)")
    portuguesa.append("Páez (Acarigua)")
    portuguesa.append("Papelón (Papelón)")
    portuguesa.append("San Genaro de Boconoíto (Boconoíto)")
    portuguesa.append("San Rafael de Onoto (San Rafael de Onoto)")
    portuguesa.append("Santa Rosalía (El Playón)")
    portuguesa.append("Sucre (Biscucuy)")
    portuguesa.append("Turén (Villa Bruzual)")

sucre = []
    sucre.append('- - Seleccione un Municipio- -')
    sucre.append("Andrés Eloy Blanco (Casanay)" )
    sucre.append("Andrés Mata (San José de Aerocuar)")
    sucre.append("Arismendi (Río Caribe)")
    sucre.append("Benítez (El Pilar)")
    sucre.append("Bermúdez (Carúpano)")
    sucre.append("Bolívar (Marigï¿½itar)")
    sucre.append("Cajigal (Yaguaraparo)")
    sucre.append("Cruz Salmerón Acosta (Araya)")
    s1ucre.append("Libertador (Tunapuy)")
    sucre.append("Mariño (Irapa)")
    sucre.append("Mejía (San Antonio del Golfo)")
    sucre.append("Montes (Cumanacoa)")
    sucre.append("Ribero (Cariaco)")
    sucre.append("Sucre (Cumaná)")
    sucre.append("Valdez (Gï¿½iria)")

tachira = []
    tachira.append('- - Seleccione un Municipio- -')
    tachira.append("Andrés Bello (Cordero)" )
    tachira.append("Antonio Rómulo Costa (Las Mesas)")
    tachira.append("Ayacucho (Colón)")
    tachira.append("Bolívar (San Antonio del Táchira)")
    tachira.append("Cárdenas (Táriba)")
    tachira.append("Córdoba (Santa Ana de Táchira)")
    tachira.append("Fernández Feo (San Rafael del Piñal)")
    tachira.append("Francisco de Miranda (San José de Bolívar)")
    tachira.append("García de Hevia (La Fru00eda)")
    tachira.append("Guásimos (Palmira)")
    tachira.append("Independencia (Capacho Nuevo)")
    tachira.append("Jáuregui (La Grita)")
    tachira.append("José María gas (El Cobre)")
    tachira.append("Junín (Rubio)")
    tachira.append("Libertad (Capacho Viejo)")
    tachira.append("Libertador (Abejales)")
    tachira.append("Lobatera (Lobatera)")
    tachira.append("Michelena (Michelena)")
    tachira.append("Panamericano (Coloncito)")
    tachira.append("Pedro María Ureña (Ureña)")
    tachira.append("Rafael Urdaneta (Delicias)")
    tachira.append("Samuel Daru00edo Maldonado (La Tendida)")
    tachira.append("San Cristóbal (San Cristóbal)")
    tachira.append("Seboruco (Seboruco)")
    tachira.append("Simón Rodríguez (San Simón)")
    tachira.append("Sucre (Queniquea)")
    tachira.append("Torbes (San Josecito)")
    tachira.append("Uribante (Pregonero)")
    tachira.append("San Judas Tadeo (Umuquena)")

trujillo = []
    trujillo.append('- - Seleccione un Municipio- -')
    trujillo.append("Andrés Bello (Santa Isabel)" )
    trujillo.append("Boconó (Boconó)")
    trujillo.append("Bolívar (Sabana Grande)")
    trujillo.append("Candelaria (Chejendé)")
    trujillo.append("Carache (Carache)")
    trujillo.append("Escuque (Escuque)")
    trujillo.append("José Felipe Márquez Cañizalez (El Paradero)")
    trujillo.append("Juan Vicente Campos Elías (Campo Elu00edas)")
    trujillo.append("La Ceiba (Santa Apolonia)")
    trujillo.append("Miranda (El Dividive)")
    trujillo.append("Monte Carmelo (Monte Carmelo)")
    trujillo.append("Motatán (Motatán)")
    trujillo.append("Pampán (Pampán)")
    trujillo.append("Pampanito (Pampanito)")
    trujillo.append("Rafael Rangel (Betijoque)")
    trujillo.append("San Rafael de Carvajal (Carvajal)")
    trujillo.append("Sucre (Sabana de Mendoza)")
    trujillo.append("Trujillo (Trujillo)")
    trujillo.append("Urdaneta (La Quebrada)")
    trujillo.append("Valera (Valera)")

vargas = []
    vargas.append('- - Seleccione un Municipio- -')
    vargas.append("Vargas (La Guaira)" )

yaracuy = []
    yaracuy.append('- - Seleccione un Municipio- -')
    yaracuy.append("Arístides Bastidas (San Pablo)" )
    yaracuy.append("Bolívar (Aroa)")
    yaracuy.append("Bruzual (Chivacoa)")
    yaracuy.append("Cocorote (Cocorote)")
    yaracuy.append("Independencia (Independencia)")
    yaracuy.append("José Antonio Páez (Sabana de Parra)")
    yaracuy.append("La Trinidad (Boraure)")
    yaracuy.append("Manuel Monge (Yumare)")
    yaracuy.append("Nirgua (Nirgua)")
    yaracuy.append("Peña (Yaritagua)")
    yaracuy.append("San Felipe (San Felipe)")
    yaracuy.append("Sucre (Guama)")
    yaracuy.append("Urachiche (Urachiche)")
    yaracuy.append("Veroes (Farriar)")

zulia = []
    zulia.append('- - Seleccione un Municipio- -')
    zulia.append("Almirante Padilla (El Toro)" )
    zulia.append("Baralt (San Timoteo)")
    zulia.append("Cabimas (Cabimas)" )
    zulia.append("Catatumbo (Encontrados)")
    zulia.append("Colón (San Carlos del Zulia)" )
    zulia.append("Francisco Javier Pulgar (Pueblo Nuevo-El Chivo)")
    zulia.append("Jesús Enrique Losada (La Concepción)" )
    zulia.append("Jesús María Semprún (Casigua El Cubo)")
    zulia.append("La Cañada de Urdaneta (Concepción)" )
    zulia.append("Lagunillas (Ciudad Ojeda)")
    zulia.append("Machiques de Perijá (Machiques)" )
    zulia.append("Mara (San Rafael del Moján)")
    zulia.append("Maracaibo (Maracaibo)" )
    zulia.append("Miranda (Los Puertos de Altagracia)")
    zulia.append("Páez (Sinamaica)" )
    zulia.append("Rosario de Perijá (La Villa del Rosario)")
    zulia.append("San Francisco (San Francisco)" )
    zulia.append("Santa Rita (Santa Rita)")
    zulia.append("Simón Bolívar (Tu00eda Juana)" )
    zulia.append("Sucre (Bobures)")
    zulia.append("Valmore Rodríguez (Bachaquero)" )
